version: 2
jobs:
  build_and_deploy:
    docker:
      - image: verdigristech/ci-base
    working_directory: ~/docker-sbt
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t verdigristech/sbt:0.13 .
      - run:
          name: Deploy container
          command: docker push verdigristech/sbt:0.13

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
